SRC = fdf.c parsing_fdf.c pixel.c \
	  keyhook.c

LBS = libft/libft.a

OBJ = $(SRC:.c=.o)

NAME = fdf

CC = gcc

CFLAGS = -Wall -Wextra -Werror -g

all : $(NAME)

$(NAME): $(OBJ)
	make bonus -C libft
	$(CC) -o $(NAME) $(OBJ) $(CFLAGS) $(LBS)  -lmlx -Lminilibx-linux -lXext -lX11 -lm 

$(OBJ) : $(SRC)
	$(CC) $(CFLAGS) -c $(SRC)

libft/libft.a :
	make -C libft

clean :
	make clean -C libft
	rm -rf *.o

fclean : clean
	make fclean -C libft
	rm -rf *.a

re : fclean all

bonus : all
